services:
  backend:
    image: sena-huellero-backend:prod
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sena-huellero-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/data:/app/data
    networks:
      - sena-network

  frontend:
    image: sena-huellero-frontend:prod
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sena-huellero-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - sena-network

networks:
  sena-network:
    driver: bridge
